[graphics]
framerate = 70

[map]
chunk_size = 0.045        # degrees
bbox_left = -84.6018      # longitude
bbox_right = -79.9002     # longitude
bbox_bottom = 24.4019     # latitude
bbox_top = 30.7015        # latitude

[viewport]
default_w = 0.8 #degrees